Desktop/pet/home/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

urlpatterns = [
    path('', views.hello, name= 'hello'),
    path('hello/', views.hello, name= 'hello'),
    path('favorites/', views.favorites, name= 'favorites'),
    path('about/', views.about, name= 'about'),
    path('contact/', views.contact, name= 'contact'),

]

Desktop/pet/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('user/',include('user.urls')),
    path('home/',include('home.urls')),
    path('',RedirectView.as_view(url='/home/',permanent=True)),
]

Desktop/pet/user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('register/', views.register, name= 'register'),
    path('login/',views.login, name="login"),
    path('logout/',views.logout,name='logout'),
]

Desktop/pet/home/models.py
from django.db import models

# Create your models here.

Desktop/pet/user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_id = models.CharField(max_length=32,unique=True,verbose_name="유저 아이디")
    user_pw = models.CharField(max_length=128,verbose_name="유저 비밀번호")
    user_name = models.CharField(max_length=16,unique=True,verbose_name="유저 이름")
    user_email = models.EmailField(max_length=128,unique=True,verbose_name="유저 이메일")
    user_register_dttm = models.DateTimeField(auto_now_add=True,verbose_name="계정 생성시간")
    
    def __str__(self):
        return self.user_name
    
    class Meta:
        db_table = 'user'
        verbose_name = '유저'
        verbose_name_plural='유저'

Desktop/pet/user/forms.py
from typing import Any, Dict
from django import forms 
from .models import User
from argon2 import PasswordHasher, exceptions

class RegisterForm(forms.ModelForm):
    user_id = forms.CharField(
        label='아이디',
        required = True,
        widget=forms.TextInput(
        attrs={
            'class' : 'user-id',
            'placeholder' : '아이디'
        }
        ),
        error_messages={'required': '아이디를 입력하세요.'}
    
    )

    user_pw = forms.CharField(
        label='비밀번호',
        required = True,
        widget=forms.PasswordInput(
        attrs={
            'class' : 'user-pw',
            'placeholder' : '비밀번호'
        }
        ),
        error_messages={'required': '비밀번호를 입력하세요.'}
    
    )
    user_pw_confirm = forms.CharField(
        label='비밀번호 확인',
        required = True,
        widget=forms.PasswordInput(
        attrs={
            'class' : 'user-pw-confirm',
            'placeholder' : '비밀번호 확인'
        }
        ),
        error_messages={'required': '비밀번호가 일치하지 않습니다.'}
    
    )
    user_name = forms.CharField(
        label='이름',
        required = True,
        widget=forms.TextInput(
        attrs={
            'class' : 'user-name',
            'placeholder' : '이름'
        }
        ),
        error_messages={'required': '닉네임을 입력해주세요.'}
    
    )
    user_email = forms.EmailField(
        label='이메일',
        required = True,
        widget=forms.EmailInput(
        attrs={
            'class' : 'user-email',
            'placeholder' : '이메일'
        }
        ),
        error_messages={'required': '이메일을 입력해주세요.'}
    
    )

    field_order =[
        'user_id',
        'user_pw',
        'user_pw_confirm',
        'user_name',
        'user_email'
    ]

    class Meta:
        model = User
        fields =[
            'user_id',
            'user_pw',
            'user_name',
            'user_email'
        ]

    def clean(self):
        cleaned_data = super().clean()

        user_id =cleaned_data.get('user_id','')
        user_pw =cleaned_data.get('user_pw','')
        user_pw_confirm =cleaned_data.get('user_pw_confirm','')
        user_name =cleaned_data.get('user_name','')
        user_email =cleaned_data.get('user_email','')

        if user_pw != user_pw_confirm:
            return self.add_error('user_pw_confirm','비밀번호가 다릅니다.')
        elif not (4 <= len(user_id)<=16):
            return self.add_error('user_id','아이디는 4~16자로 입력해 주세요.')
        elif 8 >len(user_pw):
            return self.add_error('user_pw','비밀번호는 8자 이상으로 적어주세요.')
        else:
            self.user_id =user_id
            self.user_pw =PasswordHasher().hash(user_pw)
            self.user_pw_confirm =user_pw_confirm
            self.user_name =user_name
            self.user_email =user_email



class LoginForm(forms.Form):
    user_id = forms.CharField(
        max_length=32,
        label='아이디',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'user-id',
                'placeholder' : '아이디'
            }
        ),
        error_messages={'required' : '아이디를 입력해주세요.'}

    )
    user_pw = forms.CharField(
        max_length=128,
        label='비밀번호',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'user-pw',
                'placeholder' : '비밀번호'
            }
        ),
        error_messages={'required' : '비밀번호 입력해주세요.'}

    )

    field_order = [
        'user_id',
        'user_pw',
    ]

    def clean(self):
        cleaned_data = super().clean()

        user_id = cleaned_data.get('user_id', '')
        user_pw = cleaned_data.get('user_pw', '')

        if user_id == '':
            return self.add_error('user_id', '아이디를 다시 입력해 주세요.')
        elif user_pw == '':
            return self.add_error('user_pw', '비밀번호를 다시 입력해 주세요.')
        else:
            try:
                user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                return self.add_error('user_id','아이디가 존재하지 않습니다.')
            
            try:
                PasswordHasher().verify(user.user_pw,user_pw)
            except exceptions.VerificationError:
                return self.add_error('user_pw','비밀번호가 다릅니다.')

            
            self.login_session = user.user_id

Desktop/pet/home/views.py
from django.shortcuts import render

# Create your views here.

def hello(request):
    context = {}

    login_session = request.session.get('login_session','')

    if login_session =='':
        context['login_session'] = False
    else:
        context['login_session'] = True

    return render(request, 'home/home.html')


def favorites(request):
    return render(request,'home/favorites.html')
def about(request):
    return render(request,'home/about.html')
def contact(request):
    return render(request,'home/contact.html')

Desktop/pet/user/views.py
from django.shortcuts import render, redirect
from django.db import transaction
from .models import User
from argon2 import PasswordHasher
from .forms import RegisterForm,LoginForm

def register(request):
    register_form = RegisterForm()
    context = {'forms' : register_form} 

    if request.method == 'GET':
        return render(request, 'user/register.html', context)
    
    elif request.method == 'POST':
        register_form= RegisterForm(request.POST)
        if register_form.is_valid():
            user = User(
                user_id = register_form.user_id,
                user_pw = register_form.user_pw,
                user_name = register_form.user_name,
                user_email = register_form.user_email
                )
            user.save()
            return redirect('/')
    else:
        context['forms'] = register_form
        if register_form.errors:
            for value in register_form.errors.values():
                context['error'] = value
    return render(request, 'user/register.html',context)

def login(request):
    loginform = LoginForm()
    context = {'forms' : loginform} 

    if request.method == 'GET':
        return render(request, 'user/login.html', context)
    elif request.method == 'POST':
        loginform= LoginForm(request.POST)
        
        if loginform.is_valid():
            request.session['login_session'] = loginform.login_session
            request.session.set_expiry(0)
            return redirect('/')
        else:
            context['forms'] = loginform
            if loginform.errors:
                for value in loginform.errors.values():
                    context['error'] = value
        return render(request, 'user/login.html',context)

def logout(request):
    request.session.flush()
    return redirect('/')

Desktop/pet/home/templates/home/About.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> MyPet Website</title>
    <link rel = "stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/scroll.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap');
    </style>
</head>
<body>

<div id="container">
    <header id = "header"> 
        <nav class ="menu">
            <ul>
                <li><a href = "{% url 'hello' %}" <b>Home</b></a></li>
                <li><a href = "{% url 'about' %}" <b>About</b></a></li>
                <li><a href = "{% url 'favorites' %}" <b>favorites</b></a></li>
                <li><a href = "{% url 'contact' %}" <b>Contact</b></a></li>
                {% if login_session %}
                    <li><a href="{% url 'user:logout' %}" >Logout</a></li>
                {% else %}
                    <li><a href="{% url 'user:register' %}" class="signup-btn">Signup</a></li>
                    <li><a href="{% url 'user:login' %}" class="login-btn">Login</a></li>
                {% endif %}
        </nav>
    </header> 
    <div class="list">
        <div class ="two">
            <img class = "me" src ="/static/img/mmo.jpg" alt="" width="450px;" height="500px">
            <h3 class ="intext"> <strong>Who is 몽자?<br></strong><br><br>
                Hello! I'm 몽자. Welcome to my homepage.<br><br>
                
                I'm a female Poodle. 
                I'm 7 years old this year and <br>my birthday is on April 8th. <br>
                I'm very gentle and cute personality and <br>love my family very much.
                <br>
                I enjoy various hobbies and travels, <br>
                sharing them with people <br>through social media such as YouTube and Instagram.
                <br>
                <br>
                <br>
                </h3>
        </div>
    </div>
</div>
</body>

Desktop/pet/home/templates/home/Contact.html
{% load static %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> MyPet Website</title>
        <link rel = "stylesheet" type="text/css" href="{% static 'css/index.css' %}">
        <link rel = "stylesheet" type="text/css" href="{% static 'css/scroll.css' %}">
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap');
        </style>
    </head>
    <body>

    <div id="container">
        <header id = "header"> 
            <nav class ="menu">
                <ul>
                    <li><a href = "{% url 'hello' %}" <b>Home</b></a></li>
                    <li><a href = "{% url 'about' %}" <b>About</b></a></li>
                    <li><a href = "{% url 'contact' %}" <b>Contact</b></a></li>
                    {% if login_session %}
                        <li><a href="{% url 'user:logout' %}" >Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'user:register' %}" class="signup-btn">Signup</a></li>
                        <li><a href="{% url 'user:login' %}" class="login-btn">Login</a></li>
                    {% endif %}
            </nav>
        </header> 
        <div class="list">
            <div class = "four">
                <img class = "contact_img" src ="/static/img/aaa.jpg">
                <a href="https://www.youtube.com/@MONGJA/featured" class="ct">Velog</a>
                <a href="https://instagram.com/mongja0408?igshid=NTc4MTIwNjQ2YQ==" class="ct">Insta</a>
                <a href="https://www.facebook.com/mongja0408" class="ct">Facebook</a>
            </div>
        </div>
    </div>
    </body>

Desktop/pet/home/templates/home/favorites.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> MyPet Website</title>
    <link rel = "stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/scroll.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap');
    </style>
</head>
<body>
    <div id="container">
        <header id = "header"> 
            <nav class ="menu">
                <ul>
                <li><a href = "{% url 'hello' %}" <b>Home</b></a></li>
                <li><a href = "{% url 'about' %}" <b>About</b></a></li>
                <li><a href = "{% url 'favorites' %}" <b>favorites</b></a></li>
                <li><a href = "{% url 'contact' %}" <b>Contact</b></a></li>
                {% if login_session %}
                    <li><a href="{% url 'user:logout' %}" >Logout</a></li>
                {% else %}
                    <li><a href="{% url 'user:register' %}" class="signup-btn">Signup</a></li>
                    <li><a href="{% url 'user:login' %}" class="login-btn">Login</a></li>
                {% endif %}
            </nav>
        </header> 

        <div class="list">
            <div class="three">
                <h1><br><br> 💕 💕 💕 </h1>
                <div class = "favorites">
                    <div class="lists">
                        <img class = "list_img" src="/static/img/fri.jpg" alt="">
                        <p class = "list_text">모든 강아지와 친구에요 🐶</p>
                    </div>
      
                    <div class="lists">
                        <img class = "list_img" src="/static/img/food.jpg" alt="">
                        <p class = "list_text"> 음식을 좋아해요 🥘</p>
                    </div>
      
                    <div class="lists">
                        <img class = "list_img" src="/static/img/san.jpg" alt="">
                        <p class = "list_text"> 산책도 즐기고 🏃🏻‍♂️</p>
                    </div>
      
                    <div class="lists">
                        <img class = "list_img" src="/static/img/gong.jpg" alt="">
                        <p class = "list_text"> 공놀이도 좋아해요! 💕</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

Desktop/pet/home/templates/home/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> MyPet Website</title>
    <link rel = "stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/scroll.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap');
    </style>
</head>
<body>

<div id="container">
    <header id = "header"> 
        <nav class ="menu">
            <ul>
              <li><a href = "{% url 'hello' %}" <b>Home</b></a></li>
              <li><a href = "{% url 'about' %}" <b>About</b></a></li>
              <li><a href = "{% url 'favorites' %}" <b>favorites</b></a></li>
              <li><a href = "{% url 'contact' %}" <b>Contact</b></a></li>
                {% if login_session %}
                    <li><a href="{% url 'user:logout' %}" >Logout</a></li>
                {% else %}
                    <li><a href="{% url 'user:register' %}" >Signup</a></li>
                    <li><a href="{% url 'user:login' %}" class="login-btn">Login</a></li>
                {% endif %}
        </nav>
    </header> 
  <div class="list">
      <div class="one">
        <span class="profile"><img src="/static/img/1.jpg" width="550px;" height="550px" alt=""/></span> 
        <h3><strong>Hello! I'm 린.</strong> <br></h3>
      </div>
  </div>

  <div class="list">
      <div class ="two">
          <img class = "me" src ="/static/img/2.jpg" alt="" width="450px;" height="500px">
          <h3 class ="intext"> <strong>Who is 린?<br></strong><br><br>
            Hello! I'm 린. Welcome to my homepage.<br><br>
            
            2살이에요
            <br>생일은 12월 17일이에요 <br>
            <br>lovely Poodle
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            </h3>
      </div>
  </div>
  
  <div class="list">
      <div class="three">
          <h1><br><br></h1>
          <div class = "favorites">
              <div class="lists">
                  <img class = "list_img" src="/static/img/4.jpg" alt="">
                  <p class = "list_text">리니 강아지</p>
              </div>

              <div class="lists">
                  <img class = "list_img" src="/static/img/5.jpg" alt="">
                  <p class = "list_text">같이 놀 때</p>
              </div>

              <div class="lists">
                  <img class = "list_img" src="/static/img/6.jpg" alt="">
                  <p class = "list_text"> 옷 입었을 때</p>
              </div>

              <div class="lists">
                  <img class = "list_img" src="/static/img/7.jpg" alt="">
                  <p class = "list_text"></p>
              </div>
          </div>
      </div>
  </div>

  <div class="list">
    <div class = "four">
        <img class = "contact_img" src ="/static/img/3.jpg">
        <a href="https://www.youtube.com/@MONGJA/featured" class="ct">Velog</a>
        <a href="https://instagram.com/mongja0408?igshid=NTc4MTIwNjQ2YQ==" class="ct">Insta</a>
        <a href="https://www.facebook.com/mongja0408" class="ct">Facebook</a>
    </div>
</div>
</div>
</body>

Desktop/pet/user/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html> 
<head> 
<meta charset="utf-8"> 
<title>{% block title %}Django Auth Tutorial{% endblock %}</title> </head> <body> <main> {% block content %} {% endblock %} </main> </body> 
</html>

Desktop/pet/user/templates/home.html
<!-- templates/home.html --> 
{% extends 'base.html' %}
 {% block title %}Home{% endblock %}
 {% block content %} 
{% if user.is_authenticated %} Hi {{ user.username }}!
 {% else %} 
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> 
{% endif %} 
{% endblock %}

Desktop/pet/user/templates/user/login.html
{% block contents %}
<div>로그인 페이지!</div>

<form action="" method="POST">
    {% csrf_token %}
    
    {% for form in forms%}
    <div>
        <label for="{{ form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {% endfor %}

    {% if error %}
    {{ error }}
    {% endif %}
    <button type="submit" name="login-submit" value="login">로그인하기</button>

</form>
{% endblock contents %}

Desktop/pet/user/templates/user/register.html
{% extends 'home/home.html' %}

{% block contents %}
<div>회원가입 페이지!</div>

<form action="" method="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{ form.auto_id}}">{{form.label}}</label>
        {{form}}
    </div>
    {% endfor %}

    {% for form in forms %}
    {{ form.errors}}
    {% endfor %}

    <button type="submit" name="register-submit" value="register">회원가입하기</button>
</form>
 {% endblock contents %}